from dotenv import load_dotenv
load_dotenv()
import os 

KEY = os.getenv("ACCESS_KEY")

# Topics with multi-word exact match requirements
KEYWORDS: list[str] = ['"climate protest"', '"climate strikes"', '"climate activism"']

# Tags in multiple categories
TAGS: dict[str, list[str]] = {
    "CLIMATE_ACTIVISM": [
        "environment/activism",
        "climate-academy/climate-academy",
        "a-different-christmas/series/on-the-climate-frontline",
        "environment/fossil-fuel-divestment",
        "environment/school-climate-strikes",
        "environment/greta-thunberg",
        "environment/extinction-rebellion",
        "environment/climate-camp",
        "environment/series/climate-crimes",
        "environment/just-stop-oil",
        "environment/greenpeace",
    ],
    "CLIMATE_DENIAL": [
        "environment/climate-change-scepticism",
        "global-development-professionals-network/series/climate-change-debates",
        "environment/series/climate-wars-hacked-emails",
        "environment/series/climate-consensus-the-97-percent",
        "australia-news/series/weight-of-the-world-the-climate-scientists-burden",
    ],
    "EMISSIONS": [
        "environment/carbon-emissions",
        "environment/fossil-fuels",
        "carbonreduction/carbonreduction",
        "environment/carbon-capture-and-storage",
        "environment/carbon-offset-projects",
        "environment/carbonfootprints",
        "environment/series/carbon-bombs",
        "environment/series/carbon-bombs-2022",
        "environment/series/the-carbon-footprint-of-everything",
        "environment/series/the-great-carbon-divide",
        "theguardian/carbon-challenge",
        "theguardian/carbon-challenge/carbon-challenge",
        "theguardian/carbonquestion",
        "sustainable-business/series/in-focus-mandatory-carbon-reporting",
        "sustainable-business/carbon-trust-supporter",
        "sustainable-business/low-carbon",
        "sustainable-business/series/carbon-case-studies",
        "campaign/callout/callout-low-carbon-homes",
        "sustainable-business/series/awards-2011-carbon",
        "australia-news/series/the-top-end-carbon-bomb",
        "sustainable-business/series/in-focus-carbon-finance-for-development",
    ],
    "BIODIVERSITY": [
        "environment/farming",
        "environment/amazon-rainforest",
        "environment/un-biodiversity-summit-2020",
        "environment/wildlife",
        "environment/marine-life",
        "environment/endangered-habitats",
        "environment/great-barrier-reef",
        "environment/biodiversity",
        "environment/deforestation",
        "environment/series/the-age-of-extinction",
        "environment/series/seascape-the-state-of-our-oceans",
        "environment/forests",
        "environment/logging-and-land-clearing",
        "environment/conservation" "environment/series/great-barrier-reef-in-crisis",
        "science/extinct-wildlife",
        "environment/cetaceans",
    ],
    "POLLUTION_AND_WASTE": [
        "environment/plastic",
        "environment/plastic-waste",
        "environment/recycling",
        "environment/pollution",
        "environment/air-pollution",
        "environment/waste",
        "environment/oil-sands",
    ],
    "ENERGY": [
        "environment/oil",
        "environment/energy",
        "environment/renewable-energy",
        "environment/renewableenergy",
        "environment/solarpower",
        "environment/nuclearpower",
        "environment/windpower",
        "environment/fracking",
        "environment/mining",
        "environment/coal",
    ],
    "GLOBAL_CRISIS": [
        "environment/series/overtourism-and-the-climate-crisis",
        "us-news/climate-crisis-in-the-american-west",
        "us-news/series/climate-countdown",
        "world/series/an-impossible-choice-the-pacific-climate-crisis",
        "environment/the-forgotten-climate-change-crises",
        "news/series/australia-v-the-climate",
        "environment/series/the-last-chance",
        "global-development-professionals-network/series/climate-change-defining-moments",
        "campaign/callout/us-callout-west-coast-diy-climate-crisis-solutions",
        "combating-the-climate-crisis/combating-the-climate-crisis",
        "environment/series/climate-change-too-hot-to-handle",
        "environment/series/climate-changed",
        "us-news/series/climate-change-in-the-us--the-dangers-and-the-solutions",
        "us-news/series/the-climate-report-trump-tried-to-bury",
    ],
    "EXTREME_CLIMATE_IMPACTS": [
        "environment/flooding",
        "environment/sea-ice",
        "environment/sea-level",
        "environment/sea-level-rise",
        "environment/extreme-heat",
        "environment/extreme-weather",
        "australia-news/australia-east-coast-floods-2021",
        "australia-news/australia-east-coast-floods-2022",
        "australia-news/north-queensland-floods-2023",
        "australia-news/series/fire-flood-and-plague-essays-about-2020",
        "campaign/callout/callout-canada-wildfires",
        "campaign/callout/callout-corfu-wildfires",
        "campaign/callout/callout-europe-wildfires",
        "campaign/callout/callout-flooding-aftermath",
        "campaign/callout/callout-flooding-uk-2024",
        "campaign/callout/callout-flooding-uk-2024campaign/callout/callout-libya-flooding",
        "campaign/callout/callout-greece-wildfires",
        "campaign/callout/callout-hawaii-wildfires",
        "campaign/callout/callout-libya-flooding",
        "campaign/callout/callout-rhodes-and-corfu-wildfires",
        "campaign/callout/callout-spain-flooding-october-2024",
        "campaign/callout/callout-storm-and-flooding-california-feb-2024",
        "campaign/callout/callout-storm-gerrit",
        "floodalert/floodalert",
        "uk-news/uk-floods-2014",
        "us-news/california-drought",
        "us-news/california-wildfires",
        "us-news/colorado-wildfires",
        "us-news/hurricane-harvey",
        "us-news/hurricane-helene",
        "us-news/hurricane-ian",
        "us-news/hurricane-idalia",
        "us-news/hurricane-irene",
        "us-news/hurricane-isaac",
        "us-news/hurricane-katrina",
        "us-news/hurricane-laura",
        "us-news/hurricane-michael",
        "us-news/hurricane-milton",
        "us-news/hurricane-sandy",
        "us-news/hurricanegustav",
        "world/hurricanes",
        "world/indonesia-tsunami",
        "world/indonesia-tsunami-december-2018",
        "world/libya-flood-2023",
        "world/pakistan-flood",
        "world/series/after-the-tsunami",
        "world/series/indus-river-journey-pakistan-after-the-floods",
        "world/tornadoes",
        "world/tsunami2004",
        "world/tsunamis",
        "world/wildfires",
        "world/canada-wildfires",
        "world/hurricane-dorian",
        "world/hurricane-fiona",
        "world/hurricane-florence",
        "world/hurricane-irma",
        "world/hurricane-jose",
        "world/hurricane-maria",
        "world/hurricane-matthew",
        "world/hurricane-otto",
        "us-news/us-wildfires",
        "us-news/series/hurricane-katrina-10-years-on",
        "us-news/oklahoma-city-tornado",
        "campaign/callout/uk-callout-flooding-sept-2024",
        "campaign/callout/uk-callout-living-in-a-flood-prone-area",
        "campaign/callout/uk-callout-storm-darragh",
        "campaign/callout/uk-callout-storm-eowyn",
        "campaign/callout/us-callout-california-wildfires",
        "campaign/callout/us-callout-hurricane-helene",
        "campaign/callout/us-callout-hurricane-milton",
        "campaign/callout/us-callout-winter-storm-blair",
        "campaign/callout/callout-what-we-lost-to-the-flood",
        "campaign/callout/callout-uk-farmers-and-flooding",
        "campaign/callout/callout-storm-isha",
        "environment/drought",
        "environment/series/the-floods",
        "global-development/series/2004-indian-ocean-tsunami-10-years-on",
        "environment/poles",
        "environment/series/the-rising-ocean",
        "news/series/weatherwatch",
    ],
    "CLIMATE_POLICY": [
        "australia-news/australia-cop-21-climate-conference-paris",
        "environment/global-climate-talks",
        "environment/cop-20-un-climate-change-conference-lima",
        "environment/cop-21-un-climate-change-conference-paris",
        "environment/cop26-glasgow-climate-change-conference-2021",
        "environment/cop27",
        "environment/cop28",
        "environment/green-politics",
        "environment/ipcc",
        "climate-summit/climate-summit",
        "environment/climate-aid",
        "environment/climate-consensus-97-per-cent",
        "environment/committee-on-climate-change",
        "environment/sustainable-development",
        "environment/carbon-tax",
        "environment/corporatesocialresponsibility",
        "greendeal/greendeal",
    ],
    "SIMILAR_BUT_NOT_CLIMATE": [
        # nature, unrelated to climate
        "artanddesign/once-upon-a-forest",
        "campaign/callout/callout-bird-of-the-year-poll",
        "campaign/callout/callout-new-zealand-birds-and-cats",
        "environment/series/birdwatch",
        "environment/series/nature-heroes",
        "environment/series/the-truth-about-sharks",
        "environment/series/top-10-uk-bird-songs",
        "environment/series/urban-wildlife",
        "environment/series/view-from-the-amazon",
        "environment/series/weekinwildlife",
        "environment/series/wildlife-on-your-doorstep",
        "environment/wild-flowers",
        "film/nocturnal-animals",
        "lifeandstyle/series/discover-nature",
        "lifeandstyle/series/houseplant-of-the-week",
        "lifeandstyle/series/how-does-your-garden-grow",
        "science/series/mystery-bird",
        "science/series/new-to-nature",
        "theguardian/naturespotting",
        "theguardian/naturespotting/animals",
        "theguardian/urban-wildlife/urban-wildlife-a-spotter-s-guide",
        "theobserver/naturespotting",
        "travel/top-100-wildlife-holidays",
        "travel/wildlifeholidays",
        "tv-and-radio/nature-documentaries",
        "tv-and-radio/science-and-nature-tv",
        "world/animals",
        "world/series/the-amazing-world-of-animals",
        "world/series/the-amazing-world-of-animalsenvironment/nature-up",
        "lifeandstyle/series/plant-of-the-week",
    ],
    "UNRELATED_TO_CLIMATE": [
        # tech
        "technology/big-data",
        "technology/data-visualisation",
        "technology/digitalvideo",
        "technology/e-government",
        "technology/facial-recognition",
        "technology/gadgets",
        "technology/garmin",
        "technology/hacking",
        "technology/internet-safety",
        "technology/xiaomi",
        "technology/y2k",
        "technology/yahoo-takeover",
        "media-network/series/global-tech",
        "media-network/series/next-gen-tech",
        "media-network/series/open-data-economy",
        "media-network/series/shop-talk",
        "media-network/series/technology-in-retail",
        "media-network/series/the-power-of-privacy",
        "media-network/video-advertising",
        # sports
        "sport/australia-women-s-rugby-league-team",
        "sport/australia-women-s-rugby-union-team",
        "sport/australian-ball-tampering",
        "sport/austria-womens-football-team",
        "sport/bbc-sports-personality-of-the-year",
        "sport/commonwealth-games-2018",
        "sport/concussion-in-sport",
        "sport/cricket-england-west-indies-2009",
        "sport/diversity-in-cricket",
        "sport/drugs-in-sport",
        "sport/ecb",
        "sport/england-netball-team",
        "sport/wales-rugby-league-team",
        "sport/wales-rugby-union-team",
        "sport/wales-womens-rugby-union-team",
        "sport/washington-nationals",
        "sport/winter-paralympics-2014",
        "sport/winter-paralympics-2022",
        "sport/women-s-t20-world-cup",
        "sport/women-s-t20-world-cup-2023",
        "sport/womens-t20-world-cup-2024",
        "sport/womens-world-t20-2020",
        # random
        ## "crisis"
        "business/series/eurozone-crisis-live",
        "football/clubs-in-crisis",
        "society/series/girls--mental-health-crisis",
        "politics/series/a-crisis-of-democracy",
        "australia-news/series/the-youth-gambling-crisis",
        ## "impact"
        "campaign/callout/callout-marking-boycott-impact",
        "sustainable-business/series/impact-digital-technology-on-children",
        "campaign/callout/callout-impact-of-return-to-the-office",
        ## other
        "education/series/schoolgate",
        "stage/cloud-gate-dance-theatre",
        "fashion/new-york-fashion-week-autumn-winter-2011",
        "film/a-history-of-violence",
        "lifeandstyle/series/empire-of-drinks",
        "money/series/thinking-about-money",
        "music/series/best-music-of-2016",
        "theguardian/quick-and-healthy-desserts",
        "global-development/series/the-politics-of-gender",
        "lifeandstyle/series/family-under-the-microscope-series"
        "lifeandstyle/series/sleep--a-user-s-guide",
        "science/susan-greenfield",
        "travel/taiwan",
        "world/series/french-elections-your-stories",
        "media/sunday-world",
        "media/world-press-photo-contest",
        "media/worldcupthemedia",
        "film/team-america-world-police",
        "music/series/a-history-of-folk-and-world-music",
        "music/series/new-music-from-around-the-world",
        "theguardian/second-world-war/aftermath",
        "theguardian/second-world-war/global-war",
        "theguardian/second-world-war/liberation",
        "theguardian/second-world-war/origins",
        "world/bird-flu",
        "us-news/opioids",
        "travel/nashville",
        "travel/netjetters2000sam",
        "travel/new-south-wales",
        "travel/newzealand",
        "travel/offers/srilanka",
        "travel/offers/zambia",
        "travel/onyourbikeeasyrider",
        "travel/onyourbikepedalpower",
        "travel/pakistan",
        "travel/palau",
        "world/series/youngeamerica",
        "world/southpacific",
        "world/sri-lanka-cricket-team-attack",
        "world/srilanka",
        "world/the-war-logs",
        "world/toronto-van-incident",
        "world/trans-pacific-partnership",
        "uk-news/series/brexit-one-year-to-go",
        "travel/series/rail-journey-of-the-month",
        "travel/series/readers-coronavirus-travel-questions",
        "travel/series/road-trips-usa-east-coast",
        "travel/series/road-trips-usa-pacific-coast",
        "education/series/degree-apprenticeships-in-focus",
        "education/series/degrees-that-make-a-difference",
        "education/series/donyourway",
        "education/series/early-career-researchers",
        "education/series/edgeless-university",
        "education/series/fitting-in",
        "education/series/g2-student-special",
        "campaign/email/fighting-back",
        "campaign/email/green-light",
        "campaign/email/house-to-home",
        "campaign/email/morning-briefing",
        "campaign/email/morning-mail",
        "campaign/email/observed",
        "campaign/email/observer-food",
        "campaign/email/patriarchy",
        "campaign/email/reclaim-your-brain",
        "campaign/email/saturday-edition",
        "campaign/email/the-fiver",
        "business/goldmansachs",
        "business/hewlettpackard",
        "business/hospitality-industry",
        "business/house-fraser",
        "business/ian-livingston",
        "business/iggroupholdings",
        "business/infrastructure",
        "business/institute-of-directors",
        "business/j-sainsbury",
        "business/jackson-hole-central-bank-summit",
        "books/series/the-book-i-got-for-christmas",
        "books/series/the-books-of-my-life",
        "books/series/the-doorbells-of-florence",
        "books/series/the-last-word",
        "books/series/theweekinbooks",
        "books/series/this-months-best-paperbacks",
        "books/series/thrillers-of-the-month",
        "books/series/voicesofprotest",
        "books/series/what-i-m-thinking-about",
        "books/series/whyiwrite",
        "books/series/your-weekend-reading",
    ],
}

tag_typs: dict[str, list[str]] = {
    "relevant": [
        "CLIMATE_DENIAL",  # climate sceptisim, debates, misinformation
        "EMISSIONS",  # mostly carbon emissions and carbon footprint, NOT policy related
        "ENERGY",  # clean or dirty energy
        "BIODIVERSITY",  # deforestation, endangered wildlife, biodiversity loss
        "EXTREME_CLIMATE_IMPACTS",  # ice-caps, droughts, hurricanes, wildfires, roughly similar to impactDB categories
        "GLOBAL_CRISIS",  # "climate crisis" in general, some politics
        "POLLUTION_AND_WASTE",  # pollution, waste, recycling
        "CLIMATE_ACTIVISM",  # known orgs/strikes or any climate activism
        "CLIMATE_POLICY",  # mostly UN COPs and sustainability (for example, the "environment/carbon-tax" tag lives here!)
    ],
    "irrelevant": [
        "SIMILAR_BUT_NOT_CLIMATE",  # category to make the task challenging
        "UNRELATED_TO_CLIMATE",  # completely unrelated articles
    ],
}
